# Generated by Django 5.0.6 on 2024-07-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesar', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=69)),
                ('apellido', models.CharField(max_length=69)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_contacto', models.IntegerField(choices=[(0, 'reclamo'), (1, 'trabajo'), (2, 'sugerencia'), (3, 'felicitaciones')])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
